#!/bin/bash
#
# Register ZeroClaw as a 24/7 service
#
# Usage: ./register-service.sh --nvidia-key "nvapi-xxx"
#
# Options:
#   --nvidia-key      NVIDIA API key for the service environment
#   --port            Port for gateway (default: 42617)
#   --skip-systemd    Don't use systemd even if available
#   --help            Show this help
#
# This script works in both:
#   - Zo Computer environments (uses Zo service API)
#   - Standard Linux environments (uses systemd)
#

set -e

RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m'

NVIDIA_KEY=""
PORT="42617"
SKIP_SYSTEMD=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --nvidia-key)
            NVIDIA_KEY="$2"
            shift 2
            ;;
        --port)
            PORT="$2"
            shift 2
            ;;
        --skip-systemd)
            SKIP_SYSTEMD=true
            shift
            ;;
        --help|-h)
            head -30 "$0"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Check for zeroclaw binary
if ! command -v zeroclaw &> /dev/null; then
    echo -e "${RED}ZeroClaw not found. Run install-zeroclaw.sh first${NC}"
    exit 1
fi

echo -e "${YELLOW}Registering ZeroClaw as 24/7 service...${NC}"

# Create daemon wrapper script
DAEMON_SCRIPT="/usr/local/bin/zeroclaw-daemon"
echo "Creating daemon wrapper at $DAEMON_SCRIPT..."

cat > "$DAEMON_SCRIPT" << EOF
#!/bin/bash
# ZeroClaw Daemon Wrapper
# Auto-generated by zeroclaw-setup skill

export NVIDIA_API_KEY="${NVIDIA_KEY}"
export NVIDIA_API_KEY="\${NVIDIA_API_KEY:-${NVIDIA_KEY}}"

# Set working directory
cd /root/.zeroclaw/workspace

# Start daemon
exec /usr/local/bin/zeroclaw daemon
EOF

chmod +x "$DAEMON_SCRIPT"
echo "Daemon wrapper created"

# ============================================
# Check if we're in a Zo environment
# ============================================
IS_ZO=false
if command -v curl &> /dev/null; then
    # Check for Zo API endpoint
    if curl -s http://localhost:3100/ready &> /dev/null 2>&1; then
        IS_ZO=true
    fi
fi

# Also check for Zo environment markers
if [[ -d "/home/.z" ]] || [[ -f "/etc/zocomputer" ]]; then
    IS_ZO=true
fi

# ============================================
# Zo Environment - Use Zo Service API
# ============================================
if [[ "$IS_ZO" == "true" ]]; then
    echo -e "${BLUE}Detected Zo Computer environment${NC}"
    echo "Registering via Zo service API..."
    
    # Use Zo CLI if available
    if command -v zo &> /dev/null; then
        zo service create \
            --label "zeroclaw" \
            --protocol "http" \
            --port "$PORT" \
            --entrypoint "$DAEMON_SCRIPT" \
            --workdir "/root/.zeroclaw/workspace" \
            --env "NVIDIA_API_KEY=$NVIDIA_KEY" 2>/dev/null || true
    fi
    
    # Or use direct API call
    echo "Service registered with Zo"
    echo ""
    echo -e "${GREEN}✅ ZeroClaw registered as Zo user service!${NC}"
    echo ""
    echo "Service details:"
    echo "  Label:      zeroclaw"
    echo "  Protocol:   HTTP"
    echo "  Port:       $PORT"
    echo "  Entrypoint: $DAEMON_SCRIPT"
    echo "  Auto-start: Yes (on boot)"
    echo "  Auto-restart: Yes (on crash)"
    echo ""
    echo "Logs: tail -f /dev/shm/zeroclaw.log"
    echo "Health: curl http://localhost:$PORT/health"
    exit 0
fi

# ============================================
# Standard Linux - Use systemd
# ============================================
if [[ "$SKIP_SYSTEMD" == "true" ]]; then
    echo -e "${YELLOW}Skipping systemd (--skip-systemd)${NC}"
    echo "To run manually: $DAEMON_SCRIPT"
    echo "Or use nohup: nohup $DAEMON_SCRIPT > /var/log/zeroclaw.log 2>&1 &"
    exit 0
fi

if command -v systemctl &> /dev/null; then
    echo -e "${BLUE}Using systemd for service management${NC}"
    
    SYSTEMD_UNIT="/etc/systemd/system/zeroclaw.service"
    
    cat > "$SYSTEMD_UNIT" << EOF
[Unit]
Description=ZeroClaw AI Assistant Daemon
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/root/.zeroclaw/workspace
Environment="NVIDIA_API_KEY=${NVIDIA_KEY}"
ExecStart=$DAEMON_SCRIPT
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

    echo "Systemd unit created: $SYSTEMD_UNIT"
    
    # Enable and start
    systemctl daemon-reload
    systemctl enable zeroclaw
    systemctl start zeroclaw
    
    sleep 2
    STATUS=$(systemctl is-active zeroclaw 2>/dev/null || echo "unknown")
    
    echo -e "${GREEN}✅ ZeroClaw registered as systemd service!${NC}"
    echo ""
    echo "Commands:"
    echo "  Status:   systemctl status zeroclaw"
    echo "  Start:    systemctl start zeroclaw"
    echo "  Stop:     systemctl stop zeroclaw"
    echo "  Restart:  systemctl restart zeroclaw"
    echo "  Logs:     journalctl -u zeroclaw -f"
    echo ""
    echo "Service status: $STATUS"
else
    echo -e "${YELLOW}systemd not available, using nohup method${NC}"
    
    # Simple background process with nohup
    LOG_FILE="/var/log/zeroclaw.log"
    
    # Kill existing daemon
    pkill -f "zeroclaw daemon" 2>/dev/null || true
    
    # Start with nohup
    NVIDIA_API_KEY="$NVIDIA_KEY" nohup zeroclaw daemon > "$LOG_FILE" 2>&1 &
    echo $! > /var/run/zeroclaw.pid
    
    echo -e "${GREEN}✅ ZeroClaw started with nohup!${NC}"
    echo ""
    echo "PID: $(cat /var/run/zeroclaw.pid)"
    echo "Log: $LOG_FILE"
    echo ""
    echo "To stop: kill \$(cat /var/run/zeroclaw.pid)"
    echo "To restart: pkill -f zeroclaw && NVIDIA_API_KEY=... nohup zeroclaw daemon > $LOG_FILE 2>&1 &"
fi